<?php
/**
 * AUTO-GENERATED by SFC Compiler v3 — DO NOT EDIT
 * Source: Calculator.vue
 */

const WINDOW_WIDTH  = 328;
const WINDOW_HEIGHT = 420;

function getLayout(): array
{
    return [
        'window_width'  => 328,
        'window_height' => 420,
        'elements'      => array (
  0 => 
  array (
    'type' => 'rect',
    'x' => 0,
    'y' => 0,
    'w' => 328,
    'h' => 420,
    'color' => 1973790,
  ),
  1 => 
  array (
    'type' => 'rect',
    'x' => 4,
    'y' => 4,
    'w' => 320,
    'h' => 72,
    'color' => 2960685,
  ),
  2 => 
  array (
    'type' => 'text',
    'bind' => 'expression',
    'x' => 10,
    'y' => 10,
    'align' => 'left',
    'fontSize' => 16,
    'color' => 9868950,
    'bold' => 0,
  ),
  3 => 
  array (
    'type' => 'text',
    'bind' => 'display',
    'x' => 0,
    'y' => 36,
    'align' => 'right',
    'fontSize' => 32,
    'color' => 16777215,
    'bold' => 1,
    'containerW' => 320,
    'containerX' => 4,
  ),
),
        'buttons'       => array (
  0 => 
  array (
    'label' => 'C',
    'x' => 2,
    'y' => 82,
    'w' => 76,
    'h' => 56,
    'bg' => 5263440,
    'fg' => 16777215,
    'border' => 6579300,
    'handler' => 'reset',
    'arg' => NULL,
  ),
  1 => 
  array (
    'label' => '<-',
    'x' => 82,
    'y' => 82,
    'w' => 76,
    'h' => 56,
    'bg' => 5263440,
    'fg' => 16777215,
    'border' => 6579300,
    'handler' => 'backspace',
    'arg' => NULL,
  ),
  2 => 
  array (
    'label' => '/',
    'x' => 162,
    'y' => 82,
    'w' => 76,
    'h' => 56,
    'bg' => 38399,
    'fg' => 16777215,
    'border' => 1354239,
    'handler' => 'handleButton',
    'arg' => '/',
  ),
  3 => 
  array (
    'label' => '*',
    'x' => 242,
    'y' => 82,
    'w' => 76,
    'h' => 56,
    'bg' => 38399,
    'fg' => 16777215,
    'border' => 1354239,
    'handler' => 'handleButton',
    'arg' => '*',
  ),
  4 => 
  array (
    'label' => '7',
    'x' => 2,
    'y' => 142,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '7',
  ),
  5 => 
  array (
    'label' => '8',
    'x' => 82,
    'y' => 142,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '8',
  ),
  6 => 
  array (
    'label' => '9',
    'x' => 162,
    'y' => 142,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '9',
  ),
  7 => 
  array (
    'label' => '-',
    'x' => 242,
    'y' => 142,
    'w' => 76,
    'h' => 56,
    'bg' => 38399,
    'fg' => 16777215,
    'border' => 1354239,
    'handler' => 'handleButton',
    'arg' => '-',
  ),
  8 => 
  array (
    'label' => '4',
    'x' => 2,
    'y' => 202,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '4',
  ),
  9 => 
  array (
    'label' => '5',
    'x' => 82,
    'y' => 202,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '5',
  ),
  10 => 
  array (
    'label' => '6',
    'x' => 162,
    'y' => 202,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '6',
  ),
  11 => 
  array (
    'label' => '+',
    'x' => 242,
    'y' => 202,
    'w' => 76,
    'h' => 56,
    'bg' => 38399,
    'fg' => 16777215,
    'border' => 1354239,
    'handler' => 'handleButton',
    'arg' => '+',
  ),
  12 => 
  array (
    'label' => '1',
    'x' => 2,
    'y' => 262,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '1',
  ),
  13 => 
  array (
    'label' => '2',
    'x' => 82,
    'y' => 262,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '2',
  ),
  14 => 
  array (
    'label' => '3',
    'x' => 162,
    'y' => 262,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '3',
  ),
  15 => 
  array (
    'label' => '=',
    'x' => 242,
    'y' => 262,
    'w' => 76,
    'h' => 56,
    'bg' => 16742912,
    'fg' => 16777215,
    'border' => 16748052,
    'handler' => 'calculate',
    'arg' => NULL,
  ),
  16 => 
  array (
    'label' => '0',
    'x' => 2,
    'y' => 322,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '0',
  ),
  17 => 
  array (
    'label' => '.',
    'x' => 82,
    'y' => 322,
    'w' => 76,
    'h' => 56,
    'bg' => 3289650,
    'fg' => 16777215,
    'border' => 4605510,
    'handler' => 'handleButton',
    'arg' => '.',
  ),
),
    ];
}